import type { Metadata } from "next";

import "@/app/globals.css";
import styles from "./auth.module.css"

export const metadata: Metadata = {
  title: "Ordine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    <html lang="pt-BR">
      <body>
        <main className={styles.main}>
          <section className={styles.branding}>
            <h2>Facilite a gestão do seu negócio com <span>Ordine</span></h2>
            <p>Powered by Brasilis Club</p>
          </section>
          <section className={styles.login}>
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
